In [1]:
'''
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list object containing string values while the variable array_list is a NumPy array object containing string values.

'''


import numpy as np

list_ = ['1','2','3','4','5']

array_list = np.array(object = list_)
print('Data type of list: ')

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))




Data type of list: 
Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:

'''Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list
'''
list_ = ['1','2','3','4','5']
array_list=np.array(list_)

for element in list_:
    print("The data type of list",element,'is',type(element))

for element in array_list:
    print("The data type of numpy array",element,'is',type(element))



The data type of list 1 is <class 'str'>
The data type of list 2 is <class 'str'>
The data type of list 3 is <class 'str'>
The data type of list 4 is <class 'str'>
The data type of list 5 is <class 'str'>
The data type of numpy array 1 is <class 'numpy.str_'>
The data type of numpy array 2 is <class 'numpy.str_'>
The data type of numpy array 3 is <class 'numpy.str_'>
The data type of numpy array 4 is <class 'numpy.str_'>
The data type of numpy array 5 is <class 'numpy.str_'>


In [3]:

"""Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

"""

import numpy as np

list_ = [1, 2, 3.0, 4.5, "5"]

array_list = np.array(list_, dtype=int)

print("Data types of elements in list_:")
for elem in list_:
    print(type(elem))

print("\nData types of elements in array_list:")
for elem in array_list:
    print(type(elem))


Data types of elements in list_:
<class 'int'>
<class 'int'>
<class 'float'>
<class 'float'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [4]:
'''
Q2.Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size
'''
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]

num_array = np.array(object=num_list)

# Find the shape of num_array
print("Shape of num_array:", num_array.shape)

# Find the size of num_array
print("Size of num_array:", num_array.size)



Shape of num_array: (2, 3)
Size of num_array: 6


In [5]:
'''Q5.Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]
'''
import numpy as np

# create a 3x3 array of zeros
zeros_array = np.zeros((3,3))

# print the array
print(zeros_array)




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:

'''Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]'''
import numpy as np

# create an identity matrix of shape (5,5)
identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
